# C_SRC += $(OPENWARE)/Source/crc32.c
# C_SRC += $(OPENWARE)/Source/eepromcontrol.c
# C_SRC += $(OPENWARE)/Source/errorhandlers.c
# C_SRC += $(OPENWARE)/Source/sysex.c
# C_SRC += $(OPENWARE)/Source/callbacks.c
# C_SRC += $(OPENWARE)/Source/support.c
# C_SRC += $(OPENWARE)/Source/flash-spi.c
# C_SRC += $(OPENWARE)/Source/mpu.c
# CPP_SRC += $(OPENWARE)/Source/ApplicationSettings.cpp
# CPP_SRC += $(OPENWARE)/Source/MidiHandler.cpp
# CPP_SRC += $(OPENWARE)/Source/Codec.cpp
# CPP_SRC += $(OPENWARE)/Source/MidiReader.cpp
# CPP_SRC += $(OPENWARE)/Source/operators.cpp
# CPP_SRC += $(OPENWARE)/Source/Owl.cpp
# CPP_SRC += $(OPENWARE)/Source/PatchRegistry.cpp
# CPP_SRC += $(OPENWARE)/Source/ProgramManager.cpp
# CPP_SRC += $(OPENWARE)/Source/ServiceCall.cpp
# CPP_SRC += $(OPENWARE)/Source/message.cpp
# CPP_SRC += $(OPENWARE)/Source/callbacks.cpp
# CPP_SRC += $(OPENWARE)/Source/BootloaderStorage.cpp
# CPP_SRC += $(OPENWARE)/Source/MidiWriter.cpp
# CPP_SRC += $(OPENWARE)/Source/MidiController.cpp
# CPP_SRC += $(OPENWARE)/Source/MidiReceiver.cpp
# CPP_SRC += $(OPENWARE)/Source/Storage.cpp
C_SRC_CDC_ACM_DMO_TEMPLATE = $(CHERRY)/demo/cdc_acm_template.c
C_SRC_CDC_ACM_MSC_DMO_TEMPLATE = $(CHERRY)/demo/cdc_acm_msc_template.c

C_SRC_MIC_MCH_V1_AUDIO_DMO_TEMPLATE = $(CHERRY)/demo/audio_v1_mic_multichan_template.c
C_SRC_MIC_SPK_MCH_V1_AUDIO_DMO_TEMPLATE = $(CHERRY)/demo/audio_v1_mic_speaker_multichan_template.c
C_SRC_MIC_MCH_V2_AUDIO_DMO_TEMPLATE = $(CHERRY)/demo/audio_v2_mic_multichan_template.c
C_SRC_MIC_SPK_MCH_V2_AUDIO_DMO_TEMPLATE = $(CHERRY)/demo/audio_v2_mic_speaker_multichan_template.c
